import Head from 'next/head';
import { HiSparkles } from 'react-icons/hi';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ellie Trullinger Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">developedbyellie</h1>
            <ul className="flex items-center">
              <li>
                <HiSparkles className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-slate-500 to-slate-300 text-white px-4 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div>
            <h2>Ellie Trullinger</h2>
            <h3>Software Engineer</h3>
            <p>Software Engineer with 4.5 years of experience working in the tech industry with venture-backed, high-growth startups.</p>
          </div>
        </section>
      </main>
    </div>
  );
};
